### ISSUE TITLE
Notebook code tests fail on Travis

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#1124]
@ocefpaf the notebook code tests are failing on Travis and I can't figure out why, can you help?

Here is the error message from Travis:

```
0.28s$ if [[ $TRAVIS_JOB_NAME == 'notebooks-code' ]]; then pytest --nbval-lax -p no:python /tmp/examples ; fi
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 927, in getini
    return self._inicache[name]
KeyError: 'python_files'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 934, in _getini
    description, type, default = self._parser._inidict[name]
KeyError: 'python_files'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/TEST/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 679, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 896, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 836, in _preparse
    self._consider_importhook(args)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 772, in _consider_importhook
    hook = _pytest.assertion.install_importhook(self)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 81, in install_importhook
    config._assertstate.hook = hook = rewrite.AssertionRewritingHook(config)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 63, in __init__
    self.fnpats = config.getini("python_files")
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 929, in getini
    self._inicache[name] = val = self._getini(name)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/_pytest/config/__init__.py", line 936, in _getini
    raise ValueError("unknown configuration value: %r" % (name,))
ValueError: unknown configuration value: 'python_files'
The command "if [[ $TRAVIS_JOB_NAME == 'notebooks-code' ]]; then pytest --nbval-lax -p no:python /tmp/examples ; fi" exited with 1.
```

Something with the `nbval` tests failing. `python_files` is a configuration option of Pytest so I don't understand why it would consider it unknown.

I found this issue on the `nbval` repo: https://github.com/computationalmodelling/nbval/pull/113
It suggests `nbval` doesn't work with Python 3.7 and Ubuntu Trusty on Travis. I tried using Python 3.6 and using Ubuntu Xenial but that didn't resolve the issue. See #1121 and #1123.

**Comment by ocefpaf** [comment]
> I tried using Python 3.6 and using Ubuntu Xenial but that didn't resolve the issue. See #1121 and #1123.

We don't use the `xenial` image. (We are using the minimal image and Python is installed with `miniconda`.)

I believe this may be a problem with latest `pytest`, investigating...

**Comment by ocefpaf** [comment]
The problem is the `-p no:python` option with latest pytest. We can drop it b/c there are no python files in the example directory, or we can pin pytest. I'll send a PR soon.

xref.: https://github.com/computationalmodelling/nbval/issues/114

**Comment by Conengmo** [comment]
Thanks for looking into this, good that you found out what the problem was! Your PR looks good and tests now pass so I’ll go ahead and merge it.
