### ISSUE TITLE
Can't perform this operation for unregistered loader type

### ISSUE THREAD

**Issue by Uzair919** [python-visualization/folium#1163]
**Code**
```
from tkinter import *
import glob, os
import sys
import pandas as pd
import sys
import pkg_resources
pkg_resources.NullProvider._has = lambda self, path: True

import math
import os.path
import folium
import pkg_resources
pkg_resources.NullProvider._has = lambda self, path: True
import tkinter
from tkinter import messagebox
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

import matplotlib.pyplot as plt

def find_data_file(filename):
    if getattr(sys, 'frozen', False):
        # The application is frozen
        datadir = os.path.dirname(sys.executable)
    else:
        # The application is not frozen
        # Change this bit to match where you store your data files:
        datadir = os.path.dirname(__file__)

    return os.path.join(datadir, filename)

#my_path = os.path.abspath(__file__)

master = Tk()

variable = StringVar(master)
variable.set("one")  # default value

m1 = Message(master, text="All questions/comments --> salman.zaidi@bell.ca\n"
                          "Release Date : March 29th 2019\n"
                          "Version 2.0")
m1.grid(row=4, column=2, columnspan=3)

'''
w1 = Label(master, text = "Bench mark Markets")
w2 = OptionMenu(master, variable, "one", "two", "three")
w1.grid(row=3,column=1)
w2.grid(row=3,column=2)
'''

bm_markets_list = []

os.chdir(r"\\drivedatato\DROP_BOX\BM_SCANNER_DATA")
for file in glob.glob("*.xlsx"):
    bm_markets_list.append(file[:-5])

bm_markets = Listbox(master)
bm_markets.config(relief=SUNKEN, border=2)
bm_markets.grid(row=1, column=1, sticky='w',rowspan=12)
scrollbar = Scrollbar(bm_markets, orient=VERTICAL)
bm_markets = Listbox(bm_markets, yscrollcommand=scrollbar.set)
scrollbar.config(command=bm_markets.yview)
scrollbar.pack(side=RIGHT, fill=Y)
bm_markets.pack(side=LEFT, fill=BOTH, expand=1)

for x in bm_markets_list[::-1]:
    bm_markets.insert(END, x)

Label(master, text="Available BM Markets").grid(row=0, column=1, sticky='nw', columnspan=2)

L1 = Label(master, text="Bell Channel")
L2 = Label(master, text="Rogers Channel")
L1.grid(row=1, column=2)
L2.grid(row=2, column=2)
E1 = Entry(master, bd=5)
E1.grid(row=1, column=3)
E2 = Entry(master, bd=5)
E2.grid(row=2, column=3)

import os
my_path = os.path.abspath('__file__')
def getInput():
    Bell_Channel = E1.get()
    Rogers_Channel = E2.get()
    selected_bm = bm_markets.selection_get()

    global params
    params = [Bell_Channel, Rogers_Channel, selected_bm]


def widget_remove():
    master.destroy()


b1 = Button(master, text="Delta Map", command=lambda: [getInput(), widget_remove(), my_delta()])
b1.grid(row=7, column=2)

b2 = Button(master, text="Delta CDFs", command=lambda: [getInput(), widget_remove(), my_CDF()])
b2.grid(row=7, column=3)

b3 = Button(master, text="Both", command=lambda: [getInput(), widget_remove(), my_delta(), my_CDF()])
b3.grid(row=7, column=4)


def my_delta():
    # my_directory=r"\\drivedatato\DROP_BOX\BM_SCANNER_DATA\%s.xlsx"%params[2]
    Bell = pd.read_excel(r"\\drivedatato\DROP_BOX\BM_SCANNER_DATA\%s.xlsx" % params[2])
    Bell = Bell.drop(['DB', 'CollectionName', 'Altitude', 'MsgTime', 'RSSI', 'PhCId0', 'RSRQ0'], axis=1)

    Bell_RSRP = Bell.loc[Bell['Channel'] == int(params[0])]
    Rogers_RSRP = Bell.loc[Bell['Channel'] == int(params[1])]

    Bell_RSRP = Bell_RSRP.rename(columns={'RSRP0': 'Bell_rsrp', 'SINR0': 'Bell_sinr'})
    Rogers_RSRP = Rogers_RSRP.rename(columns={'RSRP0': 'Rogers_rsrp', 'SINR0': 'Rogers_sinr'})

    Bell_RSRP['Lat_Long'] = Bell_RSRP['Longitude'].map(str) + Bell_RSRP['Latitude'].map(str)
    Rogers_RSRP['Lat_Long'] = Rogers_RSRP['Longitude'].map(str) + Rogers_RSRP['Latitude'].map(str)

    Combined = Bell_RSRP.merge(Rogers_RSRP, on='Lat_Long')
    # Bell_RSRP['Rogers_RSRP']= Rogers_RSRP['RSRP0']

    Combined['Delta_RSRP'] = Combined['Bell_rsrp'] - Combined['Rogers_rsrp']

    Combined['Delta_SINR'] = Combined['Bell_sinr'] - Combined['Rogers_sinr']

    # Combined.head(5)

    '''converting dataframe columns to lists'''
    lat = list(Combined["Latitude_x"])
    long = list(Combined["Longitude_x"])
    delta_SINR = list(Combined["Delta_SINR"])
    Bell_SINR = list(Combined['Bell_sinr'])
    Rogers_SINR = list(Combined['Rogers_sinr'])
    delta_RSRP = list(Combined["Delta_RSRP"])
    Bell_RSRP = list(Combined['Bell_rsrp'])
    Rogers_RSRP = list(Combined['Rogers_rsrp'])

    '''Initializing the map'''
    # map = folium.Map(location=[43.645921,-79.611721], zoom_start=10, tiles='OpenStreetMap',control_scale=True)
    base_map = folium.Map(location=[lat[500], long[500]], zoom_start=12, tiles='OpenStreetMap', control_scale=True)

    '''functions for legends'''

    def color_producer(Delta1):
        if Delta1 > 3:
            return 'blue'
        elif -3 <= Delta1 < 3:
            return 'yellow'
        else:
            return 'red'

    def SINR_code(SNR):
        if SNR >= 30:
            return 'yello'
        elif 20 <= SNR < 30:
            return 'green'
        elif 10 <= SNR < 20:
            return 'lime'
        elif 5 <= SNR < 10:
            return 'aqua'
        elif 0 <= SNR < 5:
            return 'blue'
        else:
            return 'red'

    def RSRP_code(Rsrp):
        if Rsrp >= -70:
            return 'red'
        elif -80 < Rsrp <= -70:
            return 'orange'
        elif -90 < Rsrp <= -80:
            return 'yellow'
        elif -100 < Rsrp <= -90:
            return 'green'
        elif -110 < Rsrp <= -100:
            return 'blue'
        else:
            return 'black'

    '''for loop through the lists'''

    fg_Bell_SINR = folium.FeatureGroup(name="Bell SINR", show=False)
    for lt, ln, bell_SINR in zip(lat, long, Bell_SINR):
        fg_Bell_SINR.add_child(
            folium.CircleMarker(location=[lt, ln], radius=2, popup='Bell SINR = ' + str(bell_SINR),
                                color=SINR_code(bell_SINR), fill_opacity=1,
                                fill_color=SINR_code(bell_SINR)))

    fg_Rogers_SINR = folium.FeatureGroup(name="Rogers SINR", show=False)
    for lt, ln, rogers_SINR in zip(lat, long, Rogers_SINR):
        fg_Rogers_SINR.add_child(
            folium.CircleMarker(location=[lt, ln], radius=2, popup='Rogers SINR = ' + str(rogers_SINR),
                                color=SINR_code(rogers_SINR), fill_opacity=1,
                                fill_color=SINR_code(rogers_SINR)))

    fg_delta_SINR = folium.FeatureGroup(name="Delta SINR", show=False)
    for lt, ln, d_SINR in zip(lat, long, delta_SINR):
        fg_delta_SINR.add_child(
            folium.CircleMarker(location=[lt, ln], radius=2, popup='Delta SINR   = ' + str(d_SINR),
                                color=color_producer(d_SINR), fill_opacity=1,
                                fill_color=color_producer(d_SINR)))

    fg_Bell_RSRP = folium.FeatureGroup(name="Bell RSRP", show=False)
    for lt, ln, bell_RSRP in zip(lat, long, Bell_RSRP):
        fg_Bell_RSRP.add_child(
            folium.CircleMarker(location=[lt, ln], radius=2, popup='Bell RSRP = ' + str(bell_RSRP),
                                color=RSRP_code(bell_RSRP), fill_opacity=1,
                                fill_color=RSRP_code(bell_RSRP)))
    fg_Rogers_RSRP = folium.FeatureGroup(name="Rogers RSRP", show=False)
    for lt, ln, rogers_RSRP in zip(lat, long, Rogers_RSRP):
        fg_Rogers_RSRP.add_child(
            folium.CircleMarker(location=[lt, ln], radius=2, popup='Rogers RSRP = ' + str(rogers_RSRP),
                                color=RSRP_code(rogers_RSRP), fill_opacity=1,
                                fill_color=RSRP_code(rogers_RSRP)))
    fg_delta_RSRP = folium.FeatureGroup(name="Delta RSRP", show=False)
    for lt, ln, d_RSRP in zip(lat, long, delta_RSRP):
        fg_delta_RSRP.add_child(
            folium.CircleMarker(location=[lt, ln], radius=2, popup='Delta RSRP  = ' + str(d_RSRP),
                                color=color_producer(d_RSRP), fill_opacity=1,
                                fill_color=color_producer(d_RSRP)))

    '''adding child maps to original maps'''
    base_map.add_child(fg_delta_SINR)
    base_map.add_child(fg_Bell_SINR)
    base_map.add_child(fg_Rogers_SINR)
    base_map.add_child(fg_delta_RSRP)
    base_map.add_child(fg_Bell_RSRP)
    base_map.add_child(fg_Rogers_RSRP)

    base_map.add_child(folium.LayerControl())
    '''saving the maps as html object'''
    base_map.save(my_path+"%s vs %s Delta_test-%s.html"%(params[0],params[1],params[2]))
   #base_map.save(r"C:\Users\uz6100822\Desktop\python_office\plot %s vs %s Delta_test-%s.html"%(params[0],params[1],params[2]))
     
def my_CDF():


    ###GUI

    my_file = pd.read_excel(r"\\drivedatato\DROP_BOX\BM_SCANNER_DATA\%s.xlsx" % params[2])
    my_file = my_file.drop(['DB', 'CollectionName', 'Altitude', 'MsgTime', 'RSSI', 'PhCId0', 'RSRQ0'], axis=1)

    Bell = my_file.loc[my_file['Channel'] == int(params[0])]
    Rogers = my_file.loc[my_file['Channel'] == int(params[1])]

    # Bell_channel=int(params[0])
    # Rogers_channel=int(params[1])

    Bell = Bell.rename(columns={'RSRP0': 'Bell_rsrp', 'SINR0': 'Bell_sinr'})
    Rogers = Rogers.rename(columns={'RSRP0': 'Rogers_rsrp', 'SINR0': 'Rogers_sinr'})

    Bell['Lat_Long'] = Bell['Longitude'].map(str) + Bell['Latitude'].map(str)
    Rogers['Lat_Long'] = Rogers['Longitude'].map(str) + Rogers['Latitude'].map(str)

    ###Bell RSRP

    Bell_RSRP = Bell.sort_values(by=['Bell_rsrp'])
    Bell_RSRP['Count'] = 'default Value'
    Bell_RSRP['CDF'] = 'default Value'
    Bell_RSRP = Bell_RSRP.groupby('Bell_rsrp').count()
    Bell_Count = Bell_RSRP['Count'].sum()
    Bell1 = list(Bell_RSRP.Count)
    Bell_RSRP = Bell_RSRP.iloc[::-1].reset_index()
    for index, row in Bell_RSRP.iterrows():
        Bell_RSRP['CDF'] = (Bell_RSRP['Count'] / Bell_Count * 100).cumsum()

    Bell_sum = Bell_RSRP['CDF'].sum()

    Bell_RSRP_X = Bell_RSRP['Bell_rsrp']
    Bell_RSRP_Y = Bell_RSRP['CDF']

    ###Rogers RSRP

    Rogers_RSRP = Rogers.sort_values(by=['Rogers_rsrp'])
    Rogers_RSRP['Count'] = 'default Value'
    Rogers_RSRP['CDF'] = 'default Value'
    Rogers_RSRP = Rogers_RSRP.groupby('Rogers_rsrp').count()
    Rogers_Count = Rogers_RSRP['Count'].sum()
    Rogers1 = list(Rogers_RSRP.Count)
    Rogers_RSRP = Rogers_RSRP.iloc[::-1].reset_index()
    for index, row in Rogers_RSRP.iterrows():
        Rogers_RSRP['CDF'] = (Rogers_RSRP['Count'] / Rogers_Count * 100).cumsum()

    Rogers_sum = Rogers_RSRP['CDF'].sum()

    Rogers_RSRP_X = Rogers_RSRP['Rogers_rsrp']
    Rogers_RSRP_Y = Rogers_RSRP['CDF']

    ###Bell SINR

    Bell_SINR = Bell.sort_values(by=['Bell_sinr'])
    Bell_SINR['Count'] = 'default Value'
    Bell_SINR['CDF'] = 'default Value'
    Bell_SINR = Bell_SINR.groupby('Bell_sinr').count()
    Bell_Count = Bell_SINR['Count'].sum()
    Bell2 = list(Bell_SINR.Count)
    Bell_SINR = Bell_SINR.iloc[::].reset_index()
    for index, row in Bell_SINR.iterrows():
        Bell_SINR['CDF'] = (Bell_SINR['Count'] / Bell_Count * 100).cumsum()

    Bell_sum = Bell_SINR['CDF'].sum()

    Bell_SINR_X = Bell_SINR['Bell_sinr']
    Bell_SINR_Y = Bell_SINR['CDF']

    ###Rogers SINR

    Rogers_SINR = Rogers.sort_values(by=['Rogers_sinr'])
    Rogers_SINR['Count'] = 'default Value'
    Rogers_SINR['CDF'] = 'default Value'
    Rogers_SINR = Rogers_SINR.groupby('Rogers_sinr').count()
    Rogers_Count = Rogers_SINR['Count'].sum()
    Rogers1 = list(Rogers_SINR.Count)
    Rogers_SINR = Rogers_SINR.iloc[::].reset_index()
    for index, row in Rogers_SINR.iterrows():
        Rogers_SINR['CDF'] = (Rogers_SINR['Count'] / Rogers_Count * 100).cumsum()

    Rogers_sum = Rogers_SINR['CDF'].sum()

    Rogers_SINR_X = Rogers_SINR['Rogers_sinr']
    Rogers_SINR_Y = Rogers_SINR['CDF']

    ####RSRP Plotting

    plt.xlabel('RSRP')
    plt.ylabel('Percentage')
    plt.title('%s v/s %s RSRP CDF' % (int(params[0]), int(params[1])))

    plt.plot(Bell_RSRP_X, Bell_RSRP_Y, 'b')
    plt.plot(Rogers_RSRP_X, Rogers_RSRP_Y, 'r')
    Bell_RSRP = mpatches.Patch(color='blue', label='Bell')
    Rogers_RSRP = mpatches.Patch(color='red', label='Rogers')
    plt.legend(handles=[Bell_RSRP, Rogers_RSRP])

    plt.grid(True)
    plt.xlim(-30, -150)
    plt.locator_params(axis='x', nbins=10)
    plt.savefig(my_path+"%s vs %s RSRP-CDF-%s.png"%(params[0],params[1],params[2]))   
   
    plt.savefig(r"C:\Users\uz6100822\Desktop\python_office\plot\ %s vs %s SINR-CDF-%s"%(params[0],params[1],params[2]))
    ####SINR Plotting

    plt.xlabel('SINR')
    plt.ylabel('Percentage')
    plt.title('%s v/s %s SINR CDF' % (int(params[0]), int(params[1])))

    plt.plot(Bell_SINR_X, Bell_SINR_Y, 'b')
    plt.plot(Rogers_SINR_X, Rogers_SINR_Y, 'r')
    Bell_SINR = mpatches.Patch(color='blue', label='Bell')
    Rogers_SINR = mpatches.Patch(color='red', label='Rogers')
    plt.legend(handles=[Bell_SINR, Rogers_SINR])

    plt.grid(True)
    plt.xlim(-30, 40)
    plt.savefig(my_path+"%s vs %s SINR-CDF-%s.png"%(params[0],params[1],params[2]))  
    plt.savefig(r"C:%s vs %s uzi-%s.png"%(params[0],params[1],params[2]))
    #plt.savefig(r"C:\Users\uz6100822\Desktop\python_office\plot %s vs %s SINR-CDF-%s"%(params[0],params[1],params[2]))

mainloop()

def _init_numpy_mkl():
    # Numpy+MKL on Windows only
    import os
    import ctypes
    if os.name != 'nt':
        return
    # disable Intel Fortran default console event handler
    env = 'FOR_DISABLE_CONSOLE_CTRL_HANDLER'
    if env not in os.environ:
        os.environ[env] = '1'
    # preload MKL DLLs from numpy.core
    try:
        _core = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'core')
        for _dll in ('mkl_rt', 'libiomp5md', 'mkl_core', 'mkl_intel_thread',
                     'libmmd', 'libifcoremd', 'libimalloc'):
            ctypes.cdll.LoadLibrary(os.path.join(_core,_dll))
    except Exception:
        pass

_init_numpy_mkl()
del _init_numpy_mkl

```

### **Problem description
my exe initially works fine but when plot and map function are called , it crashes** i get following error message 
`C:\Users\uz6100822\Desktop\dist\brand>brand.exe Exception in Tkinter callback Traceback (most recent call last): File "tkinter\__init__.py", line 1705, in __call__ File "brand.py", line 110, in <lambda> File "brand.py", line 149, in my_delta File "site-packages\folium\folium.py", line 283, in __init__ File "site-packages\folium\raster_layers.py", line 98, in __init__ File "site-packages\jinja2\environment.py", line 749, in list_templates File "site-packages\jinja2\loaders.py", line 265, in list_templates File "site-packages\jinja2\loaders.py", line 259, in _walk File "site-packages\pkg_resources\__init__.py", line 1432, in resource_listdir File "site-packages\pkg_resources\__init__.py", line 1474, in _listdir NotImplementedError: Can't perform this operation for unregistered loader type`

**### Expected Output
no-crash

**### Output of ``folium.__version__****
`0.9.1'

**Comment by Conengmo** [comment]
folium is maintained by volunteers, so unfortunately we don't have the capacity to help out with these more advanced use cases. I'm closing the issue since we can't support .exe creation at the moment. If anybody can help out with this issue that's of course very welcome.
