### ISSUE TITLE
Coordinates (LAT and LON) marker 

### ISSUE THREAD

**Issue by JuanCalvoFerrandiz** [python-visualization/folium#1333]
**Describe the solution you'd like**
I need a search bar so users can input a location, by Latitude and Longitude, and the map will automatically put a temporary marker or take to that location.

**Additional context**
I have done some research and I understand, if nothing has been done till the date, it feels it will be some kind of mixture between **MousePosition()** and **Search()** plugins. I also found this link that I think is related: http://zyzo.github.io/gsoc/fossasia/2015/05/03/gsoc-map-picker-task.html Any help or comments a very welcome! :) 

Thanks for this amazing work. I hope that in the near future, when I get a little more fluent with big python projects, I can contribute to this fantastic project.

**Comment by Conengmo** [comment]
Hi @JuanCalvoFerrandiz, good to hear you like this library! Coincidently we have a PR pending that implements the feature you describe: https://github.com/python-visualization/folium/pull/1323 If you can install folium from that git branch you can test it out. I'm curious to hear if it works for you.

**Comment by JuanCalvoFerrandiz** [comment]
Sounds great. 

I having problems using de plugin. I have done the installation of the branch, and I see in my new plugins folder, the control_geocoder.py, but I'm not able to call the class. The constructor I can call is LocateGeocoder(), but when I run it, as it is describe here: https://github.com/python-visualization/folium/issues/1321#issuecomment-625355298, I have this error: 
`Traceback (most recent call last):
  File "C:\Users\juanc\Anaconda3\envs\project_jalvos\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-653d0a053cb7>", line 2, in <module>
    import folium.plugins
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\juanc\Anaconda3\envs\project_jalvos\lib\site-packages\folium\plugins\__init__.py", line 24, in <module>
    from folium.plugins.locate_geocoder import LocateGeocoder
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'folium.plugins.locate_geocoder'`

on the other hand, I'm not sure what I'm expecting to achieve and how to use this class for my purpose of finding any LAT/LON position. :) Thanks! Any help is welcome.

**Comment by JuanCalvoFerrandiz** [comment]
Actually the error happens just with:
`import folium.plugins`

This is the branch I installed:
![Capture 666JPG](https://user-images.githubusercontent.com/20303036/82434745-9c37e400-9a93-11ea-9e67-6c354b927496.JPG)

Please, let me know how I can help with more testing.

**Comment by Conengmo** [comment]
I renamed the class, please import it as follows:

```
from folium.plugins import Geocoder
Geocoder().add_to(m)
```

or

```
import folium.plugins
folium.plugins.Geocoder().add_to(m)
```

**Comment by JuanCalvoFerrandiz** [comment]
Hi, 
I just make a new installatation: >pip install git+https://github.com/WBP20/foliu
m.git, and same error with just first line: `import folium.plugins`

`Traceback (most recent call last):
  File "C:\Users\juanc\Anaconda3\envs\project_2004\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-3545e1d94389>", line 1, in <module>
    import folium.plugins
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\juanc\Anaconda3\envs\project_jalvos\lib\site-packages\folium\plugins\__init__.py", line 24, in <module>
    from folium.plugins.locate_geocoder import LocateGeocoder
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'folium.plugins.locate_geocoder'
import folium.plugins
Traceback (most recent call last):
  File "C:\Users\juanc\Anaconda3\envs\project_jalvos\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-3545e1d94389>", line 1, in <module>
    import folium.plugins
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\juanc\Anaconda3\envs\project_jalvos\lib\site-packages\folium\plugins\__init__.py", line 24, in <module>
    from folium.plugins.locate_geocoder import LocateGeocoder
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'folium.plugins.locate_geocoder'
`
I'm doing something worng?

**Comment by Conengmo** [comment]
You're almost there, you're not specifying the branch to install from so it will take the master branch by default. The new functionality is in a branch called `WBP20-patch-1`:

`pip install git+https://github.com/WBP20/folium.git@WBP20-patch-1`

**Comment by JuanCalvoFerrandiz** [comment]
Fantastic! It works like a charm! Great job mates.

**Comment by Conengmo** [comment]
Good to hear! The PR has been merged, so if you install folium from the master branch the functionality is there. It will also be in the next release (date still unknown).

`pip install git+https://github.com/python-visualization/folium.git`
