### ISSUE TITLE
Folium package is not working for Mac M1 Chip

### ISSUE THREAD

**Issue by mberat** [python-visualization/folium#1778]
**Describe the bug**
The folium package is not working for Mac M1 Chip.
It fails when loading the package"
Import folium 

**Environment (please complete the following information):**
 - Python version: 3.8.10
 - folium version: 0.14.0
 - branca version: 0.6.0

**Additional context**
I'm using PyCharm for Mac M1 chip which also runs the corresponding Python for Mac (i.e, import platform; print(platform.processor()) returns me "arm" as opposed to "intel bla bla bla"). 

**Possible solutions**
Newer pandas and numpy version have already addressed this issue. Maybe what has been done there can be tried?

folium is maintained by volunteers. Can you help making a fix for this issue?
I wish but I'm not a Software Engineer and have very little knowledge about inner workings of all these packages

**Comment by ocefpaf** [comment]
Folium is a pure python package, no compiled parts, making it, in theory, ready to run on M1 without any changes.

Can you provide more details? How are you installing it? What is the error message?

**Comment by mberat** [comment]
I'm using pip or pycharm's package manager to install my packages. 
Here is the full output of the error (notice the last line):
```
Traceback (most recent call last):
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/requests/compat.py", line 11, in <module>
    import chardet
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'chardet'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/folium/__init__.py", line 17, in <module>
    from folium.features import (
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/folium/features.py", line 12, in <module>
    import requests
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/cd.py", line 9, in <module>
    from .md import is_suspiciously_successive_range
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/md.cpython-38-darwin.so, 0x0002): tried: '/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/md.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/md.cpython-38-darwin.so' (no such file), '/Users/m0a0hd6/Desktop/Ambient_Visualisation/ARTON_Visuzalization/venv/lib/python3.8/site-packages/charset_normalizer/md.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```

**Comment by ocefpaf** [comment]
Yep. You problem, based on the message you posted, is with the charset-normalizer, a requests dependency. Closing this one.
