### ISSUE TITLE
ValueError: Locations is empty.

### ISSUE THREAD

**Issue by yangyang-studio** [python-visualization/folium#1845]
Traceback (most recent call last):

  File "d:\anaconda3\lib\site-packages\folium\utilities.py", line 99, in validate_locations
    next(iter(locations))

StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "F:\原始代码存放区\0329\03311507.py", line 88, in <module>
    san_map = txt_map_process(san_map)

  File "F:\原始代码存放区\0329\03311507.py", line 74, in txt_map_process
    san_map = PlotLineOnMap(Lat_lists, Lon_lists,san_map,n)

  File "F:\原始代码存放区\0329\03311507.py", line 12, in PlotLineOnMap
    line = folium.PolyLine(tri,dash_array=[10, 0],color='red').add_to(san_map) #dash_array=[10, 5] 表示线段由一段长为10的实线和一段长为5的空白区域交替组成

  File "d:\anaconda3\lib\site-packages\folium\vector_layers.py", line 169, in __init__
    super().__init__(locations, popup=popup, tooltip=tooltip)

  File "d:\anaconda3\lib\site-packages\folium\vector_layers.py", line 119, in __init__
    self.locations = validate_locations(locations)

  File "d:\anaconda3\lib\site-packages\folium\utilities.py", line 101, in validate_locations
    raise ValueError("Locations is empty.")

ValueError: Locations is empty.

The above is the error report. I look forward to hearing from you. Thank you!

![4b6ff4e0bba64ed6bd6601cd54f1f34](https://github.com/python-visualization/folium/assets/84533790/b249233e-5062-4df0-bffe-a8335b993521)

**Comment by Conengmo** [comment]
Something wrong with your data, make sure it has the right format and is filled correctly before passing it to Folium.
