### ISSUE TITLE
pip installing from pypi doesn't install jinja

### ISSUE THREAD

**Issue by zalew** [python-visualization/folium#307]
Hi

    ╰─$ pip install folium
    Collecting folium
    Installing collected packages: folium
    Running setup.py install for folium
    Successfully installed folium-0.1.6

    ╰─$ python -c 'import folium'
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/zalew/.virtualenvs/playground3/local/lib/python2.7/site-packages/folium/__init__.py", line 6, in <module>
    from folium.folium import Map
    File "/home/zalew/.virtualenvs/playground3/local/lib/python2.7/site-packages/folium/folium.py", line 19, in <module>
    from jinja2 import Environment, PackageLoader
    ImportError: No module named jinja2

The problem lies here:

    64: with open('requirements.txt') as f:
    65:     tests_require = f.readlines()
    66: install_requires = [t.strip() for t in tests_require]

Submitting fix.

Thank you for your work on this application!

**Comment by ocefpaf** [comment]
This is fixed in master.  In the past we did not specified the dependencies.
