### ISSUE TITLE
Choropleth - data key missing in source data

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#498]
I've noticed that if a key exists in the geojson features list but it is missing in the source dataset used to colour regions in a choropleth map, an error is thrown, as described here: https://github.com/python-visualization/folium/pull/456#issuecomment-244945704 .

It would be useful if we could define a "missing_color" attribute that eg colours areas of the map with an optionally specified default color (black, for example, perhaps with maximum transparency).

**Comment by ocefpaf** [comment]
@psychemedia can you share the JSON file with a [sscce](http://sscce.org/) that shows the issue?

**Comment by jeffcjohnson** [comment]
I was running into this too and then found this gist with all the pieces to show how to do it properly but it too is now failing so I think this is a regression.

https://gist.github.com/wrobstory/5609889#file-choro-py

Download and unzip the gist zip.

```
wget https://gist.github.com/wrobstory/5609889/archive/d03fa21d0c88712ab6bcdec0ee8ae682ec9b3c2e.zip
unzip d03fa21d0c88712ab6bcdec0ee8ae682ec9b3c2e.zip
cd 5609889-d03fa21d0c88712ab6bcdec0ee8ae682ec9b3c2e/
```

```
python3 choro.py

/usr/local/lib/python3.5/site-packages/folium/folium.py:504: UserWarning: This method is deprecated. Please use Map.choropleth instead.
  warnings.warn('This method is deprecated. '
/usr/local/lib/python3.5/site-packages/folium/folium.py:506: FutureWarning: 'threshold_scale' default behavior has changed. Now you get a linear scale between the 'min' and the 'max' of your data. To get former behavior, use folium.utilities.split_six.
  return self.choropleth(*args, **kwargs)
choro.py:32: FutureWarning: Map.create_map is deprecated. Use Map.save instead
  map_1.create_map(path='map_1.html')
Traceback (most recent call last):
  File "choro.py", line 32, in <module>
    map_1.create_map(path='map_1.html')
  File "/usr/local/lib/python3.5/site-packages/folium/folium.py", line 127, in create_map
    self.save(path)
  File "/usr/local/lib/python3.5/site-packages/folium/element.py", line 153, in save
    html = root.render(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/folium/element.py", line 359, in render
    child.render(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/folium/element.py", line 667, in render
    element.render(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/folium/features.py", line 480, in render
    super(TopoJson, self).render(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/folium/element.py", line 663, in render
    figure.script.add_children(Element(script(self, kwargs)),
  File "/usr/local/lib/python3.5/site-packages/jinja2/runtime.py", line 436, in __call__
    return self._func(*arguments)
  File "<template>", line 15, in macro
  File "/usr/local/lib/python3.5/site-packages/jinja2/runtime.py", line 196, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/folium/features.py", line 475, in style_data
    feature.setdefault('properties', {}).setdefault('style', {}).update(self.style_function(feature))  # noqa
  File "/usr/local/lib/python3.5/site-packages/folium/folium.py", line 673, in style_function
    "fillColor": color_scale_fun(x)
  File "/usr/local/lib/python3.5/site-packages/folium/folium.py", line 661, in color_scale_fun
    [u for u in color_domain if
  File "/usr/local/lib/python3.5/site-packages/folium/folium.py", line 662, in <listcomp>
    u <= color_data[get_by_key(x, key_on)]])]
KeyError: '0500000US72013'
```

```
pip3 freeze | grep folium
folium==0.2.1
```

**Comment by joshuacano** [comment]
I've experienced this problem as well and would be glad to work on it, once I complete my last pr.

**Comment by ocefpaf** [comment]
> I've experienced this problem as well and would be glad to work on it, once I complete my last pr.

That was fixed in latest master. See https://github.com/python-visualization/folium/pull/456 and http://nbviewer.jupyter.org/gist/ocefpaf/24f18048a7718efa76e9f9d3999bd98b

(I need to get a new release out ASAP!)
